/**
 * statusOutbox — IndexedDB-backed write-ahead log for flashcard group status
 * mutations (favorite / red-list).
 *
 * Clara Master Phase 5 invariants enforced here:
 *   - No network in `onMutate`. The mutation only writes a pending operation
 *     into IndexedDB; a background drainer pushes it to the RPC.
 *   - Every operation carries a stable `operationId` (uuid). The server-side
 *     RPC `set_flashcard_group_status` is idempotent on that id, so a replay
 *     after reload or network failure produces the same final state.
 *   - Operations are scoped by `userId`. Logging in as a different account
 *     never drains another user's pending writes.
 *   - This module is additive. It does not delete, replace, or alter any
 *     existing favorite/red-list code path.
 */

const DB_NAME = "ape-status-outbox";
const DB_VERSION = 1;
const STORE = "operations";

export type OutboxState = "pending" | "inflight" | "failed";

export interface OutboxOp {
  /** Primary key. UUID, generated by the caller, sent to the RPC. */
  operationId: string;
  userId: string;
  statusGroupUid: string;
  isFavorite: boolean;
  isRedList: boolean;
  createdAt: number;
  updatedAt: number;
  state: OutboxState;
  attempts: number;
  lastError?: string | null;
}

function isBrowser(): boolean {
  return typeof indexedDB !== "undefined";
}

function openDB(): Promise<IDBDatabase> {
  return new Promise((resolve, reject) => {
    if (!isBrowser()) {
      reject(new Error("IndexedDB unavailable"));
      return;
    }
    const req = indexedDB.open(DB_NAME, DB_VERSION);
    req.onupgradeneeded = () => {
      const db = req.result;
      if (!db.objectStoreNames.contains(STORE)) {
        const store = db.createObjectStore(STORE, { keyPath: "operationId" });
        store.createIndex("by_user", "userId", { unique: false });
        store.createIndex("by_user_group", ["userId", "statusGroupUid"], { unique: false });
      }
    };
    req.onsuccess = () => resolve(req.result);
    req.onerror = () => reject(req.error);
  });
}

async function run<T>(mode: IDBTransactionMode, fn: (store: IDBObjectStore) => T | Promise<T>): Promise<T> {
  const db = await openDB();
  return new Promise<T>((resolve, reject) => {
    const tx = db.transaction(STORE, mode);
    const store = tx.objectStore(STORE);
    let out: T;
    Promise.resolve(fn(store)).then((r) => { out = r; }).catch(reject);
    tx.oncomplete = () => resolve(out!);
    tx.onerror = () => reject(tx.error);
    tx.onabort = () => reject(tx.error);
  });
}

function reqAsPromise<T>(req: IDBRequest<T>): Promise<T> {
  return new Promise<T>((resolve, reject) => {
    req.onsuccess = () => resolve(req.result);
    req.onerror = () => reject(req.error);
  });
}

export async function enqueue(op: Omit<OutboxOp, "createdAt" | "updatedAt" | "state" | "attempts">): Promise<OutboxOp> {
  const record: OutboxOp = {
    ...op,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    state: "pending",
    attempts: 0,
    lastError: null,
  };
  await run("readwrite", (store) => reqAsPromise(store.put(record)));
  return record;
}

export async function listForUser(userId: string): Promise<OutboxOp[]> {
  return run("readonly", async (store) => {
    const idx = store.index("by_user");
    const results: OutboxOp[] = [];
    return new Promise<OutboxOp[]>((resolve, reject) => {
      const cursorReq = idx.openCursor(IDBKeyRange.only(userId));
      cursorReq.onsuccess = () => {
        const cursor = cursorReq.result;
        if (cursor) {
          results.push(cursor.value as OutboxOp);
          cursor.continue();
        } else {
          resolve(results);
        }
      };
      cursorReq.onerror = () => reject(cursorReq.error);
    });
  });
}

export async function listPendingForUser(userId: string): Promise<OutboxOp[]> {
  const all = await listForUser(userId);
  return all.filter((op) => op.state !== "inflight");
}

export async function latestForGroup(userId: string, statusGroupUid: string): Promise<OutboxOp | null> {
  const all = await listForUser(userId);
  const matches = all.filter((o) => o.statusGroupUid === statusGroupUid);
  if (matches.length === 0) return null;
  matches.sort((a, b) => b.updatedAt - a.updatedAt);
  return matches[0];
}

export async function markInflight(operationId: string): Promise<void> {
  await run("readwrite", async (store) => {
    const existing = await reqAsPromise<OutboxOp | undefined>(store.get(operationId));
    if (!existing) return;
    existing.state = "inflight";
    existing.updatedAt = Date.now();
    existing.attempts += 1;
    await reqAsPromise(store.put(existing));
  });
}

export async function markSuccess(operationId: string): Promise<void> {
  await run("readwrite", (store) => reqAsPromise(store.delete(operationId)));
}

export async function markFailed(operationId: string, error: string): Promise<void> {
  await run("readwrite", async (store) => {
    const existing = await reqAsPromise<OutboxOp | undefined>(store.get(operationId));
    if (!existing) return;
    existing.state = "failed";
    existing.lastError = error;
    existing.updatedAt = Date.now();
    await reqAsPromise(store.put(existing));
  });
}

/**
 * Reset an operation back to `pending` so the next drain attempt picks it up.
 * Used by the retry loop when the network comes back online.
 */
export async function requeueFailed(userId: string): Promise<number> {
  return run("readwrite", async (store) => {
    const all = await new Promise<OutboxOp[]>((resolve, reject) => {
      const out: OutboxOp[] = [];
      const idxReq = store.index("by_user").openCursor(IDBKeyRange.only(userId));
      idxReq.onsuccess = () => {
        const c = idxReq.result;
        if (c) { out.push(c.value as OutboxOp); c.continue(); }
        else resolve(out);
      };
      idxReq.onerror = () => reject(idxReq.error);
    });
    let requeued = 0;
    for (const op of all) {
      if (op.state === "failed") {
        op.state = "pending";
        op.updatedAt = Date.now();
        await reqAsPromise(store.put(op));
        requeued++;
      }
    }
    return requeued;
  });
}

/** Test-only: wipe the outbox completely. */
export async function __resetOutboxForTests(): Promise<void> {
  if (!isBrowser()) return;
  await new Promise<void>((resolve, reject) => {
    const req = indexedDB.deleteDatabase(DB_NAME);
    req.onsuccess = () => resolve();
    req.onerror = () => reject(req.error);
    req.onblocked = () => resolve();
  });
}