export const floatingOrderActionClass = [
  "fixed",
  "bottom-[calc(env(safe-area-inset-bottom)+5.75rem)]",
  "right-3",
  "z-[60]",
  "max-w-[calc(100vw-1.5rem)]",
  "gap-2",
  "whitespace-nowrap",
  "border-primary/30",
  "bg-background/95",
  "px-3",
  "text-xs",
  "shadow-xl",
  "backdrop-blur",
  "supports-[backdrop-filter]:bg-background/85",
  "sm:text-sm",
  "md:bottom-6",
  "md:right-6",
  "md:max-w-none",
].join(" ");
