-- Future-proof: explicitly deny Broadcast/Presence on realtime.messages.
-- App only uses postgres_changes (inherits source-table RLS); this guards against
-- accidental Broadcast/Presence usage by a future library/config change.
-- realtime.messages is platform-owned and already protected by Supabase.
-- Direct RLS and policy mutations are rejected by current local stacks.
