-- Super Importador Global V1: histórico, idempotência e RLS.
CREATE TABLE IF NOT EXISTS public.global_import_batches (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  request_id uuid NOT NULL,
  payload_hash text NOT NULL,
  package_name text NOT NULL,
  schema_version integer NOT NULL CHECK (schema_version = 1),
  status text NOT NULL DEFAULT 'processing' CHECK (status IN ('processing', 'completed', 'undone')),
  options jsonb NOT NULL DEFAULT '{}'::jsonb,
  summary jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  undone_at timestamptz,
  UNIQUE (user_id, request_id)
);

CREATE TABLE IF NOT EXISTS public.global_import_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id uuid NOT NULL REFERENCES public.global_import_batches(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  entity_type text NOT NULL CHECK (entity_type IN ('folder', 'list', 'card')),
  entity_id uuid,
  action text NOT NULL CHECK (action IN ('created', 'reused', 'skipped')),
  item_path text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_global_import_batches_user_created ON public.global_import_batches(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_global_import_items_batch ON public.global_import_items(batch_id, id);
CREATE INDEX IF NOT EXISTS idx_global_import_items_entity ON public.global_import_items(entity_type, entity_id) WHERE entity_id IS NOT NULL;

ALTER TABLE public.global_import_batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.global_import_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users manage own global import batches" ON public.global_import_batches;
CREATE POLICY "Users manage own global import batches" ON public.global_import_batches
FOR ALL TO authenticated USING ((SELECT auth.uid()) = user_id) WITH CHECK ((SELECT auth.uid()) = user_id);

DROP POLICY IF EXISTS "Users manage own global import items" ON public.global_import_items;
CREATE POLICY "Users manage own global import items" ON public.global_import_items
FOR ALL TO authenticated USING ((SELECT auth.uid()) = user_id) WITH CHECK ((SELECT auth.uid()) = user_id);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.global_import_batches TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.global_import_items TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.global_import_items_id_seq TO authenticated;
