CREATE TABLE IF NOT EXISTS public.global_import_batches (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  package_name text NOT NULL,
  schema_version integer NOT NULL,
  status text NOT NULL DEFAULT 'completed',
  options jsonb NOT NULL DEFAULT '{}'::jsonb,
  summary jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  undone_at timestamptz
);

CREATE TABLE IF NOT EXISTS public.global_import_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id uuid NOT NULL REFERENCES public.global_import_batches(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  entity_type text NOT NULL,
  entity_id uuid,
  action text NOT NULL,
  item_path text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.global_import_batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.global_import_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users manage own global import batches" ON public.global_import_batches;
CREATE POLICY "Users manage own global import batches"
  ON public.global_import_batches FOR ALL TO authenticated
  USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "Users manage own global import items" ON public.global_import_items;
CREATE POLICY "Users manage own global import items"
  ON public.global_import_items FOR ALL TO authenticated
  USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
