-- Superseded by the focused layered-import migrations that follow.
-- Kept intentionally as a no-op so timestamp ordering remains stable.
-- The active integrity rules begin in 20260701183500_layered_card_integrity.sql.
