-- Infrastructure for the canonical App Piteco store package pipeline.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'piteco-store',
  'piteco-store',
  true,
  8388608,
  array['image/avif', 'image/webp', 'image/png', 'image/jpeg']
)
on conflict (id) do update set
  name = excluded.name,
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create table if not exists public.store_package_sync_log (
  id bigint generated by default as identity primary key,
  package_id text not null,
  action text not null check (action in ('publish', 'archive')),
  version integer not null check (version > 0),
  asset_hashes jsonb not null default '{}'::jsonb,
  source text not null default 'store-packages',
  synced_at timestamptz not null default now()
);

alter table public.store_package_sync_log enable row level security;

revoke all on table public.store_package_sync_log from anon, authenticated;
grant select on table public.store_package_sync_log to authenticated;
grant all on table public.store_package_sync_log to service_role;

drop policy if exists "Developer admins can read store sync log"
on public.store_package_sync_log;

create policy "Developer admins can read store sync log"
on public.store_package_sync_log
for select
to authenticated
using (public.is_developer_admin(auth.uid()));

comment on table public.store_package_sync_log is
'Audit trail for package publish and archive operations performed by the canonical store-packages pipeline.';
