BEGIN;

CREATE TABLE IF NOT EXISTS public.web_vital_samples (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_view_id uuid NOT NULL,
  metric text NOT NULL CHECK (metric IN ('LCP', 'INP', 'CLS')),
  value double precision NOT NULL,
  rating text NOT NULL CHECK (rating IN ('good', 'needs-improvement', 'poor')),
  route_group text NOT NULL,
  device_class text NOT NULL CHECK (device_class IN ('mobile', 'tablet', 'desktop')),
  navigation_type text NOT NULL CHECK (navigation_type IN ('navigate', 'reload', 'back_forward', 'prerender', 'unknown')),
  sample_rate double precision NOT NULL CHECK (sample_rate > 0 AND sample_rate <= 1),
  build_id text,
  observed_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT web_vital_samples_page_metric_unique UNIQUE (page_view_id, metric),
  CONSTRAINT web_vital_samples_route_group_safe CHECK (
    char_length(route_group) BETWEEN 1 AND 160
    AND route_group LIKE '/%'
    AND route_group NOT LIKE '%?%'
    AND route_group NOT LIKE '%#%'
    AND route_group NOT LIKE '%@%'
    AND route_group !~ '[[:cntrl:]]'
  ),
  CONSTRAINT web_vital_samples_build_id_safe CHECK (
    build_id IS NULL OR (
      char_length(build_id) BETWEEN 1 AND 80
      AND build_id !~ '[[:cntrl:]]'
    )
  ),
  CONSTRAINT web_vital_samples_metric_range CHECK (
    (metric = 'CLS' AND value >= 0 AND value <= 10)
    OR (metric IN ('LCP', 'INP') AND value >= 0 AND value <= 60000)
  )
);

CREATE INDEX IF NOT EXISTS idx_web_vital_samples_observed_at
  ON public.web_vital_samples (observed_at DESC);
CREATE INDEX IF NOT EXISTS idx_web_vital_samples_segment
  ON public.web_vital_samples (metric, device_class, route_group, observed_at DESC);

ALTER TABLE public.web_vital_samples ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.web_vital_samples FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.web_vital_samples TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.web_vital_samples_id_seq TO service_role;

CREATE OR REPLACE FUNCTION public.record_web_vital_sample(
  _page_view_id uuid,
  _metric text,
  _value double precision,
  _rating text,
  _route_group text,
  _device_class text,
  _navigation_type text,
  _sample_rate double precision,
  _build_id text DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_metric text := UPPER(BTRIM(COALESCE(_metric, '')));
  v_rating text := LOWER(BTRIM(COALESCE(_rating, '')));
  v_route text := BTRIM(COALESCE(_route_group, ''));
  v_device text := LOWER(BTRIM(COALESCE(_device_class, '')));
  v_navigation text := LOWER(BTRIM(COALESCE(_navigation_type, '')));
  v_build text := NULLIF(BTRIM(COALESCE(_build_id, '')), '');
  v_expected_rating text;
BEGIN
  IF auth.role() <> 'service_role' THEN
    RAISE EXCEPTION 'PERMISSION_DENIED' USING ERRCODE = '42501';
  END IF;

  IF _page_view_id IS NULL THEN
    RAISE EXCEPTION 'INVALID_PAGE_VIEW_ID' USING ERRCODE = '22023';
  END IF;

  IF v_metric NOT IN ('LCP', 'INP', 'CLS') THEN
    RAISE EXCEPTION 'INVALID_METRIC' USING ERRCODE = '22023';
  END IF;

  IF _value IS NULL
     OR NOT (
       _value > '-Infinity'::double precision
       AND _value < 'Infinity'::double precision
     ) THEN
    RAISE EXCEPTION 'INVALID_VALUE' USING ERRCODE = '22023';
  END IF;

  IF (v_metric = 'CLS' AND (_value < 0 OR _value > 10))
     OR (v_metric IN ('LCP', 'INP') AND (_value < 0 OR _value > 60000)) THEN
    RAISE EXCEPTION 'VALUE_OUT_OF_RANGE' USING ERRCODE = '22023';
  END IF;

  v_expected_rating := CASE
    WHEN v_metric = 'LCP' AND _value <= 2500 THEN 'good'
    WHEN v_metric = 'LCP' AND _value <= 4000 THEN 'needs-improvement'
    WHEN v_metric = 'LCP' THEN 'poor'
    WHEN v_metric = 'INP' AND _value <= 200 THEN 'good'
    WHEN v_metric = 'INP' AND _value <= 500 THEN 'needs-improvement'
    WHEN v_metric = 'INP' THEN 'poor'
    WHEN v_metric = 'CLS' AND _value <= 0.1 THEN 'good'
    WHEN v_metric = 'CLS' AND _value <= 0.25 THEN 'needs-improvement'
    ELSE 'poor'
  END;

  IF v_rating <> v_expected_rating THEN
    RAISE EXCEPTION 'INVALID_RATING' USING ERRCODE = '22023';
  END IF;

  IF char_length(v_route) NOT BETWEEN 1 AND 160
     OR v_route NOT LIKE '/%'
     OR v_route LIKE '%?%'
     OR v_route LIKE '%#%'
     OR v_route LIKE '%@%'
     OR v_route ~ '[[:cntrl:]]' THEN
    RAISE EXCEPTION 'INVALID_ROUTE_GROUP' USING ERRCODE = '22023';
  END IF;

  IF v_device NOT IN ('mobile', 'tablet', 'desktop') THEN
    RAISE EXCEPTION 'INVALID_DEVICE_CLASS' USING ERRCODE = '22023';
  END IF;

  IF v_navigation NOT IN ('navigate', 'reload', 'back_forward', 'prerender', 'unknown') THEN
    RAISE EXCEPTION 'INVALID_NAVIGATION_TYPE' USING ERRCODE = '22023';
  END IF;

  IF _sample_rate IS NULL
     OR NOT (
       _sample_rate > '-Infinity'::double precision
       AND _sample_rate < 'Infinity'::double precision
     )
     OR _sample_rate <= 0
     OR _sample_rate > 1 THEN
    RAISE EXCEPTION 'INVALID_SAMPLE_RATE' USING ERRCODE = '22023';
  END IF;

  IF v_build IS NOT NULL AND (char_length(v_build) > 80 OR v_build ~ '[[:cntrl:]]') THEN
    RAISE EXCEPTION 'INVALID_BUILD_ID' USING ERRCODE = '22023';
  END IF;

  INSERT INTO public.web_vital_samples (
    page_view_id,
    metric,
    value,
    rating,
    route_group,
    device_class,
    navigation_type,
    sample_rate,
    build_id,
    observed_at
  ) VALUES (
    _page_view_id,
    v_metric,
    _value,
    v_rating,
    v_route,
    v_device,
    v_navigation,
    _sample_rate,
    v_build,
    now()
  )
  ON CONFLICT (page_view_id, metric) DO UPDATE
  SET value = EXCLUDED.value,
      rating = EXCLUDED.rating,
      route_group = EXCLUDED.route_group,
      device_class = EXCLUDED.device_class,
      navigation_type = EXCLUDED.navigation_type,
      sample_rate = EXCLUDED.sample_rate,
      build_id = EXCLUDED.build_id,
      observed_at = now();
END;
$$;

REVOKE ALL ON FUNCTION public.record_web_vital_sample(uuid, text, double precision, text, text, text, text, double precision, text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.record_web_vital_sample(uuid, text, double precision, text, text, text, text, double precision, text) TO service_role;

CREATE OR REPLACE VIEW public.web_vital_daily_summary
WITH (security_invoker = true, security_barrier = true)
AS
SELECT
  date_trunc('day', observed_at) AS day,
  metric,
  device_class,
  route_group,
  COUNT(*)::bigint AS sample_count,
  percentile_cont(0.75) WITHIN GROUP (ORDER BY value) AS p75_value,
  AVG(CASE WHEN rating = 'good' THEN 1.0 ELSE 0.0 END) AS good_rate,
  MIN(value) AS min_value,
  MAX(value) AS max_value
FROM public.web_vital_samples
GROUP BY 1, 2, 3, 4;

REVOKE ALL ON public.web_vital_daily_summary FROM PUBLIC, anon, authenticated;
GRANT SELECT ON public.web_vital_daily_summary TO service_role;

CREATE OR REPLACE FUNCTION public.purge_web_vital_samples(_retention_days integer DEFAULT 90)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_deleted integer;
BEGIN
  IF auth.role() <> 'service_role' THEN
    RAISE EXCEPTION 'PERMISSION_DENIED' USING ERRCODE = '42501';
  END IF;

  IF _retention_days IS NULL OR _retention_days < 7 OR _retention_days > 730 THEN
    RAISE EXCEPTION 'INVALID_RETENTION_DAYS' USING ERRCODE = '22023';
  END IF;

  DELETE FROM public.web_vital_samples
  WHERE observed_at < now() - make_interval(days => _retention_days);
  GET DIAGNOSTICS v_deleted = ROW_COUNT;
  RETURN v_deleted;
END;
$$;

REVOKE ALL ON FUNCTION public.purge_web_vital_samples(integer) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.purge_web_vital_samples(integer) TO service_role;

COMMENT ON TABLE public.web_vital_samples IS
  'Sampled first-party Core Web Vitals without user identifiers, raw URLs or query parameters.';
COMMENT ON FUNCTION public.record_web_vital_sample(uuid, text, double precision, text, text, text, text, double precision, text) IS
  'Service-only validated upsert for one LCP, INP or CLS sample per ephemeral page view.';
COMMENT ON VIEW public.web_vital_daily_summary IS
  'Service-only daily p75 summary segmented by metric, device class and normalized route group.';

COMMIT;
